name: Feature Request
description: Suggest a new feature for Loom
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: One sentence describing the feature
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful? What problem does it solve?
      placeholder: Describe the use case and why this feature would be valuable
    validations:
      required: true

  - type: textarea
    id: detailed_description
    attributes:
      label: Detailed Description
      description: Describe the feature in detail
      placeholder: How should this feature work? What should the API look like?
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you envision using this feature
      render: loom
      placeholder: |
        // Example Loom code showing how the feature would be used
        fn example() void {
            // Your example here
        }

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Loom would this affect?
      options:
        - Language Syntax
        - Type System
        - Standard Library
        - Compiler
        - Build System
        - Tools
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve my workflow
        - High - Blocking my use of Loom
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: How do other languages solve this problem? What workarounds exist?

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have seloomhed existing issues to ensure this is not a duplicate
          required: true
        - label: I have considered how this fits with Loom's design principles
          required: true