name: Performance Issue
description: Report a performance problem with Loom
title: "[PERF] "
labels: ["performance", "needs-triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem
    validations:
      required: true

  - type: textarea
    id: benchmark
    attributes:
      label: Benchmark Code
      description: Minimal code that demonstrates the performance issue
      render: loom
    validations:
      required: true

  - type: textarea
    id: measurements
    attributes:
      label: Performance Measurements
      description: Actual timing/memory measurements
      placeholder: |
        - Current performance: X seconds, Y MB memory
        - Expected performance: Based on [comparison/theory]
        - Profiling data: [if available]

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System specifications for benchmarking
      placeholder: |
        - CPU: [e.g. Intel i7-10700K, Apple M1]
        - RAM: [e.g. 16GB DDR4-3200]
        - OS: [e.g. Ubuntu 22.04]
        - Loom Version: [e.g. 0.1.0-dev]
        - Compilation flags: [e.g. -O3, --release]