name: Question
description: Ask a question about Loom
title: "[QUESTION] "
labels: ["question", "needs-triage"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know about Loom?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Language Features
        - Standard Library
        - Build System
        - Installation
        - Performance
        - Best Practices
        - Contributing
        - Other

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish?

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already tried or reseloomhed?

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have seloomhed existing issues and discussions
          required: true
        - label: I have checked the documentation
          required: true